//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_Graphique.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_Graphique.Languages.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les travaux de sauvegarde sont terminés.
        /// </summary>
        internal static string all_wb_finished {
            get {
                return ResourceManager.GetString("all_wb_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegardes.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du travail de sauvegarde.
        /// </summary>
        internal static string backup_work_name {
            get {
                return ResourceManager.GetString("backup_work_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu d&apos;édition de travail de sauvegarde.
        /// </summary>
        internal static string backups_work_edit_menu {
            get {
                return ResourceManager.GetString("backups_work_edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu d&apos;exécution de travail de sauvegarde.
        /// </summary>
        internal static string backups_work_run_menu {
            get {
                return ResourceManager.GetString("backups_work_run_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octets.
        /// </summary>
        internal static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer la langue.
        /// </summary>
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;extension des logs.
        /// </summary>
        internal static string change_log_extension {
            get {
                return ResourceManager.GetString("change_log_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un travail de sauvegarde à modifier.
        /// </summary>
        internal static string choose_backup_work_to_edit {
            get {
                return ResourceManager.GetString("choose_backup_work_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un travail de sauvegarde à exécuter.
        /// </summary>
        internal static string choose_backup_work_to_run {
            get {
                return ResourceManager.GetString("choose_backup_work_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quel fichier log souhaitez-vous ouvrir ?.
        /// </summary>
        internal static string choose_log {
            get {
                return ResourceManager.GetString("choose_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moniteur de copie.
        /// </summary>
        internal static string copy_monitor {
            get {
                return ResourceManager.GetString("copy_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string copy_status {
            get {
                return ResourceManager.GetString("copy_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier en cours de copie.
        /// </summary>
        internal static string current_file_in_copy {
            get {
                return ResourceManager.GetString("current_file_in_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir travail de sauvegarde.
        /// </summary>
        internal static string define_work {
            get {
                return ResourceManager.GetString("define_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINÉ.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de destination.
        /// </summary>
        internal static string dst_folder {
            get {
                return ResourceManager.GetString("dst_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de destination du travail de sauvergarde.
        /// </summary>
        internal static string dst_folder_backup_work {
            get {
                return ResourceManager.GetString("dst_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur, le travail de sauvegarde n&apos;a pas été configuré.
        /// </summary>
        internal static string err_empty_bw {
            get {
                return ResourceManager.GetString("err_empty_bw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun log n&apos;est disponible. Lancez votre premier travail de sauvegarde..
        /// </summary>
        internal static string error_msg_no_logs {
            get {
                return ResourceManager.GetString("error_msg_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string exit_menu {
            get {
                return ResourceManager.GetString("exit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter le programme.
        /// </summary>
        internal static string exit_program {
            get {
                return ResourceManager.GetString("exit_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier ouvert.
        /// </summary>
        internal static string file_opened {
            get {
                return ResourceManager.GetString("file_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier (rien pour garder).
        /// </summary>
        internal static string folder_or_none {
            get {
                return ResourceManager.GetString("folder_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici vos options.
        /// </summary>
        internal static string here_your_options {
            get {
                return ResourceManager.GetString("here_your_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du travail de sauvegarde.
        /// </summary>
        internal static string name_backup_work {
            get {
                return ResourceManager.GetString("name_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (rien pour garder, &apos;r&apos; pour réinitialiser).
        /// </summary>
        internal static string name_or_none {
            get {
                return ResourceManager.GetString("name_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N°.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° (&apos;a&apos; pour tous).
        /// </summary>
        internal static string number_or_all {
            get {
                return ResourceManager.GetString("number_or_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier de configuration.
        /// </summary>
        internal static string open_settings_dir {
            get {
                return ResourceManager.GetString("open_settings_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de fichier restants.
        /// </summary>
        internal static string remaining_file_number {
            get {
                return ResourceManager.GetString("remaining_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer travail de sauvegarde.
        /// </summary>
        internal static string run_work {
            get {
                return ResourceManager.GetString("run_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours.
        /// </summary>
        internal static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegardes.
        /// </summary>
        internal static string saves {
            get {
                return ResourceManager.GetString("saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionnez l&apos;extension.
        /// </summary>
        internal static string select_extension {
            get {
                return ResourceManager.GetString("select_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionnez une langue.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un log.
        /// </summary>
        internal static string show_log_in_logs_folder {
            get {
                return ResourceManager.GetString("show_log_in_logs_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsieur.
        /// </summary>
        internal static string sir {
            get {
                return ResourceManager.GetString("sir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier source.
        /// </summary>
        internal static string src_folder {
            get {
                return ResourceManager.GetString("src_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier source du travail de sauvegarde.
        /// </summary>
        internal static string src_folder_backup_work {
            get {
                return ResourceManager.GetString("src_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de début.
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copie en cours.
        /// </summary>
        internal static string starting_copy {
            get {
                return ResourceManager.GetString("starting_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de fichier total.
        /// </summary>
        internal static string total_file_number {
            get {
                return ResourceManager.GetString("total_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type du travail de sauvegarde.
        /// </summary>
        internal static string type_backup_work {
            get {
                return ResourceManager.GetString("type_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complète.
        /// </summary>
        internal static string type_complete {
            get {
                return ResourceManager.GetString("type_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différencielle.
        /// </summary>
        internal static string type_differencial {
            get {
                return ResourceManager.GetString("type_differencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapez ENTRER pour continuer.
        /// </summary>
        internal static string type_enter_to_continue {
            get {
                return ResourceManager.GetString("type_enter_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (1:complète / 2:différencielle / rien pour garder).
        /// </summary>
        internal static string type_option_or_none {
            get {
                return ResourceManager.GetString("type_option_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans EasySave !.
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monde.
        /// </summary>
        internal static string world {
            get {
                return ResourceManager.GetString("world", resourceCulture);
            }
        }
    }
}
