//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_Graphique.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_Graphique.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All backup works finished.
        /// </summary>
        public static string all_wb_finished {
            get {
                return ResourceManager.GetString("all_wb_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup Work name.
        /// </summary>
        public static string backup_work_name {
            get {
                return ResourceManager.GetString("backup_work_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup works edit menu.
        /// </summary>
        public static string backups_work_edit_menu {
            get {
                return ResourceManager.GetString("backups_work_edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup work run menu.
        /// </summary>
        public static string backups_work_run_menu {
            get {
                return ResourceManager.GetString("backups_work_run_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change extension.
        /// </summary>
        public static string change_log_extension {
            get {
                return ResourceManager.GetString("change_log_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose backup work to edit.
        /// </summary>
        public static string choose_backup_work_to_edit {
            get {
                return ResourceManager.GetString("choose_backup_work_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose backup work to run.
        /// </summary>
        public static string choose_backup_work_to_run {
            get {
                return ResourceManager.GetString("choose_backup_work_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which log file would you like to open?.
        /// </summary>
        public static string choose_log {
            get {
                return ResourceManager.GetString("choose_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy monitor.
        /// </summary>
        public static string copy_monitor {
            get {
                return ResourceManager.GetString("copy_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string copy_status {
            get {
                return ResourceManager.GetString("copy_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current file in copy.
        /// </summary>
        public static string current_file_in_copy {
            get {
                return ResourceManager.GetString("current_file_in_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define backup job(s).
        /// </summary>
        public static string define_work {
            get {
                return ResourceManager.GetString("define_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DONE.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination folder.
        /// </summary>
        public static string dst_folder {
            get {
                return ResourceManager.GetString("dst_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination folder of backup work.
        /// </summary>
        public static string dst_folder_backup_work {
            get {
                return ResourceManager.GetString("dst_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit saves.
        /// </summary>
        public static string edit_save {
            get {
                return ResourceManager.GetString("edit_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error, the backup work selected is not configured.
        /// </summary>
        public static string err_empty_bw {
            get {
                return ResourceManager.GetString("err_empty_bw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No log is available. Run your first backup work..
        /// </summary>
        public static string error_msg_no_logs {
            get {
                return ResourceManager.GetString("error_msg_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute saves.
        /// </summary>
        public static string execute_save {
            get {
                return ResourceManager.GetString("execute_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string exit_menu {
            get {
                return ResourceManager.GetString("exit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit program.
        /// </summary>
        public static string exit_program {
            get {
                return ResourceManager.GetString("exit_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File opened.
        /// </summary>
        public static string file_opened {
            get {
                return ResourceManager.GetString("file_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finished.
        /// </summary>
        public static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder (none to keep).
        /// </summary>
        public static string folder_or_none {
            get {
                return ResourceManager.GetString("folder_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here are your options:.
        /// </summary>
        public static string here_your_options {
            get {
                return ResourceManager.GetString("here_your_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of backup work.
        /// </summary>
        public static string name_backup_work {
            get {
                return ResourceManager.GetString("name_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name (none to keep, &apos;r&apos; to reset).
        /// </summary>
        public static string name_or_none {
            get {
                return ResourceManager.GetString("name_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No..
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No. (&apos;a&apos; for all).
        /// </summary>
        public static string number_or_all {
            get {
                return ResourceManager.GetString("number_or_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open settigns directory.
        /// </summary>
        public static string open_settings_dir {
            get {
                return ResourceManager.GetString("open_settings_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remaining file number.
        /// </summary>
        public static string remaining_file_number {
            get {
                return ResourceManager.GetString("remaining_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start backup job(s).
        /// </summary>
        public static string run_work {
            get {
                return ResourceManager.GetString("run_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        public static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves.
        /// </summary>
        public static string saves {
            get {
                return ResourceManager.GetString("saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select extension.
        /// </summary>
        public static string select_extension {
            get {
                return ResourceManager.GetString("select_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select language.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a log.
        /// </summary>
        public static string show_log_in_logs_folder {
            get {
                return ResourceManager.GetString("show_log_in_logs_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sir.
        /// </summary>
        public static string sir {
            get {
                return ResourceManager.GetString("sir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder.
        /// </summary>
        public static string src_folder {
            get {
                return ResourceManager.GetString("src_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder of backup work.
        /// </summary>
        public static string src_folder_backup_work {
            get {
                return ResourceManager.GetString("src_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start time.
        /// </summary>
        public static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying.
        /// </summary>
        public static string starting_copy {
            get {
                return ResourceManager.GetString("starting_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total file number.
        /// </summary>
        public static string total_file_number {
            get {
                return ResourceManager.GetString("total_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of backup work.
        /// </summary>
        public static string type_backup_work {
            get {
                return ResourceManager.GetString("type_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string type_complete {
            get {
                return ResourceManager.GetString("type_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differencial.
        /// </summary>
        public static string type_differencial {
            get {
                return ResourceManager.GetString("type_differencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type ENTER to continue.
        /// </summary>
        public static string type_enter_to_continue {
            get {
                return ResourceManager.GetString("type_enter_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type (1:complete / 2:differencial / none to keep).
        /// </summary>
        public static string type_option_or_none {
            get {
                return ResourceManager.GetString("type_option_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome in EasySave.
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à World.
        /// </summary>
        public static string world {
            get {
                return ResourceManager.GetString("world", resourceCulture);
            }
        }
    }
}
