//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_Graphique.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_Graphique.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All backup works finished.
        /// </summary>
        public static string all_wb_finished {
            get {
                return ResourceManager.GetString("all_wb_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Work name.
        /// </summary>
        public static string backup_work_name {
            get {
                return ResourceManager.GetString("backup_work_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup works edit menu.
        /// </summary>
        public static string backups_work_edit_menu {
            get {
                return ResourceManager.GetString("backups_work_edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup work run menu.
        /// </summary>
        public static string backups_work_run_menu {
            get {
                return ResourceManager.GetString("backups_work_run_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change extension.
        /// </summary>
        public static string change_log_extension {
            get {
                return ResourceManager.GetString("change_log_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup work to edit.
        /// </summary>
        public static string choose_backup_work_to_edit {
            get {
                return ResourceManager.GetString("choose_backup_work_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup work to run.
        /// </summary>
        public static string choose_backup_work_to_run {
            get {
                return ResourceManager.GetString("choose_backup_work_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which log file would you like to open?.
        /// </summary>
        public static string choose_log {
            get {
                return ResourceManager.GetString("choose_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy monitor.
        /// </summary>
        public static string copy_monitor {
            get {
                return ResourceManager.GetString("copy_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string copy_status {
            get {
                return ResourceManager.GetString("copy_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file in copy.
        /// </summary>
        public static string current_file_in_copy {
            get {
                return ResourceManager.GetString("current_file_in_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define backup job(s).
        /// </summary>
        public static string define_work {
            get {
                return ResourceManager.GetString("define_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        public static string dst_folder {
            get {
                return ResourceManager.GetString("dst_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder of backup work.
        /// </summary>
        public static string dst_folder_backup_work {
            get {
                return ResourceManager.GetString("dst_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit saves.
        /// </summary>
        public static string edit_save {
            get {
                return ResourceManager.GetString("edit_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, the backup work selected is not configured.
        /// </summary>
        public static string err_empty_bw {
            get {
                return ResourceManager.GetString("err_empty_bw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log is available. Run your first backup work..
        /// </summary>
        public static string error_msg_no_logs {
            get {
                return ResourceManager.GetString("error_msg_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute saves.
        /// </summary>
        public static string execute_save {
            get {
                return ResourceManager.GetString("execute_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit_menu {
            get {
                return ResourceManager.GetString("exit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit program.
        /// </summary>
        public static string exit_program {
            get {
                return ResourceManager.GetString("exit_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opened.
        /// </summary>
        public static string file_opened {
            get {
                return ResourceManager.GetString("file_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder (none to keep).
        /// </summary>
        public static string folder_or_none {
            get {
                return ResourceManager.GetString("folder_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are your options:.
        /// </summary>
        public static string here_your_options {
            get {
                return ResourceManager.GetString("here_your_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of backup work.
        /// </summary>
        public static string name_backup_work {
            get {
                return ResourceManager.GetString("name_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (none to keep, &apos;r&apos; to reset).
        /// </summary>
        public static string name_or_none {
            get {
                return ResourceManager.GetString("name_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. (&apos;a&apos; for all).
        /// </summary>
        public static string number_or_all {
            get {
                return ResourceManager.GetString("number_or_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settigns directory.
        /// </summary>
        public static string open_settings_dir {
            get {
                return ResourceManager.GetString("open_settings_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining file number.
        /// </summary>
        public static string remaining_file_number {
            get {
                return ResourceManager.GetString("remaining_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start backup job(s).
        /// </summary>
        public static string run_work {
            get {
                return ResourceManager.GetString("run_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        public static string saves {
            get {
                return ResourceManager.GetString("saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select extension.
        /// </summary>
        public static string select_extension {
            get {
                return ResourceManager.GetString("select_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a log.
        /// </summary>
        public static string show_log_in_logs_folder {
            get {
                return ResourceManager.GetString("show_log_in_logs_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sir.
        /// </summary>
        public static string sir {
            get {
                return ResourceManager.GetString("sir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string src_folder {
            get {
                return ResourceManager.GetString("src_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder of backup work.
        /// </summary>
        public static string src_folder_backup_work {
            get {
                return ResourceManager.GetString("src_folder_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string starting_copy {
            get {
                return ResourceManager.GetString("starting_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total file number.
        /// </summary>
        public static string total_file_number {
            get {
                return ResourceManager.GetString("total_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of backup work.
        /// </summary>
        public static string type_backup_work {
            get {
                return ResourceManager.GetString("type_backup_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string type_complete {
            get {
                return ResourceManager.GetString("type_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differencial.
        /// </summary>
        public static string type_differencial {
            get {
                return ResourceManager.GetString("type_differencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ENTER to continue.
        /// </summary>
        public static string type_enter_to_continue {
            get {
                return ResourceManager.GetString("type_enter_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (1:complete / 2:differencial / none to keep).
        /// </summary>
        public static string type_option_or_none {
            get {
                return ResourceManager.GetString("type_option_or_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in EasySave.
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string world {
            get {
                return ResourceManager.GetString("world", resourceCulture);
            }
        }
    }
}
